# Generated by Django 3.0.7 on 2021-04-06 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210326_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cartUserPost', models.ForeignKey(db_column='cartUserPost_id', on_delete=django.db.models.deletion.CASCADE, related_name='cartUserPost', to=settings.AUTH_USER_MODEL)),
                ('cartUserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartUserProfile', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Post')),
            ],
        ),
    ]
